### ISSUE TITLE
error

### ISSUE THREAD

**Issue by shanow7** [qeeqbox/social-analyzer#1]
![image](https://user-images.githubusercontent.com/37192410/102139129-b127fa80-3e5d-11eb-889d-35e5c5f98ab9.png)

no results, but the profil exists https://www.facebook.com/jan.bor.7169/ 

can you help?

**Comment by giga-a** [comment]
Hi! Yes, let me check..

**Comment by giga-a** [comment]
Fixed! it will be pushed if test passes...

**Comment by giga-a** [comment]
Passed the automated test and added in 1.03 https://github.com/qeeqbox/social-analyzer/commit/52dbf5c7e9da41eab7c618944942a219e6ad3924

A new feature was added FindUserProflesSpecial

**Comment by giga-a** [comment]
![1 04](https://user-images.githubusercontent.com/52905881/102175184-dadc2400-3e53-11eb-9630-4e665b8a92c6.png)
