### ISSUE TITLE
Linux Node WebApp installation is failing

### ISSUE THREAD

**Issue by MonetenBube** [qeeqbox/social-analyzer#105]
**Hi to everyone!** 
I encounter a small problem when I try to install the latest WebApp version on Linux.

## Issue
When I try to install the Linux Node WebApp (commit **1ff2918** or **4c42dc4**) I get the following error:

```
social-analyzer$  npm install
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for n@8.2.0: wanted {"os":"win32"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    win32
npm ERR! notsup Valid Arch:  undefined
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/test/.npm/_logs/2023-05-06T08_27_10_537Z-debug-0.log
```
_The [2023-05-06T08_27_10_537Z-debug-0.log](https://github.com/qeeqbox/social-analyzer/files/11412038/2023-05-06T08_27_10_537Z-debug-0.log) is attached. I followed the provided [installation guide](https://github.com/qeeqbox/social-analyzer#linux-as-node-webapp) for the WebApp on Linux._

## Workaround
When I switch to a earlier commit for example **607d833** or **cd84ba0** the installation is working flawlessly.
And I'm able to launch the WebApp.

## System
os: Ubuntu 23.04
kernel: 6.2.0-20-generic
npm version: 9.2.0
nodejs version: v18.13.0

**Thanks for your work!**

**Comment by spacew0rmx** [comment]
npm update
npm install
npm install loadash
npm start

**Comment by MonetenBube** [comment]
Thanks a lot and for the quick reply. 

**npm update** did the trick. Maybe it should get included in the installation guide to prevent issues in the future.
