### ISSUE TITLE
error

### ISSUE THREAD

**Issue by shanow7** [qeeqbox/social-analyzer#2]
![image](https://user-images.githubusercontent.com/37192410/102178423-aa24da80-3ea5-11eb-82d6-61f9f9a270f3.png)

nothing has changed still no results, what's wrong?

npm start                                                                      

> social-analyzer@1.0.0 start
> node server.js

Server started at http://localhost:9005/app.html
Driver Session Issue
Total time 320
(node:10846) UnhandledPromiseRejectionWarning: WebDriverError: Process unexpectedly closed with status 1
    at Object.throwDecodedError (/home/osint/social-analyzer/node_modules/selenium-webdriver/lib/error.js:550:15)
    at parseHttpResponse (/home/osint/social-analyzer/node_modules/selenium-webdriver/lib/http.js:565:13)
    at Executor.execute (/home/osint/social-analyzer/node_modules/selenium-webdriver/lib/http.js:491:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:10846) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:10846) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Driver Session Issue
Total time 249
(node:10846) UnhandledPromiseRejectionWarning: WebDriverError: Process unexpectedly closed with status 1
    at Object.throwDecodedError (/home/osint/social-analyzer/node_modules/selenium-webdriver/lib/error.js:550:15)
    at parseHttpResponse (/home/osint/social-analyzer/node_modules/selenium-webdriver/lib/http.js:565:13)
    at Executor.execute (/home/osint/social-analyzer/node_modules/selenium-webdriver/lib/http.js:491:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:10846) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)

**Comment by giga-a** [comment]
I'll take a look tomorrow! Out of curiosity, have you tried running the docker version of this?

**Comment by shanow7** [comment]
┌──(root💀tlosint)-[/home/osint]
└─# git clone https://github.com/qeeqbox/social-analyzer.git
Cloning into 'social-analyzer'...
remote: Enumerating objects: 85, done.
remote: Counting objects: 100% (85/85), done.
remote: Compressing objects: 100% (78/78), done.
remote: Total 85 (delta 42), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (85/85), 27.26 MiB | 12.55 MiB/s, done.
Resolving deltas: 100% (42/42), done.
┌──(root💀tlosint)-[/home/osint]
└─# cd social-analyzer
┌──(root💀tlosint)-[/home/osint/social-analyzer]
└─# sudo docker build -t social-analyzer . && sudo docker run -p 9005:9005 -it social-analyzer
sudo: docker: command not found

**Comment by giga-a** [comment]
Regarding the first issue - I believe that you might have an incompatible Firefox version

Regarding the second issue - You will need to install docker in order to run those commands, here are some helpful docs https://docs.docker.com/engine/install/ubuntu/
