### ISSUE TITLE
hackerone profiles not detected

### ISSUE THREAD

**Issue by PinkDev1** [qeeqbox/social-analyzer#24]
I've tested on [my own profile](hackerone.com/pinkdev1), and [stefanofinding's profile](hackerone.com/stefanofinding), but nothing came up. I'm using the tags `FindUserProfilesSlow, ShowUserProfilesSlow, FindUserProfilesSpecial` on the web interface.
Selected "hackerone" on advanced options. No google API, no proxy, and default user-agent string.

I tested it beforehand with my github profile and it did detect that one.

**Comment by giga-a** [comment]
Hey, thanks for submitting your first issue!!

Your profile and the other profile are detected (Fast tag: Rate: **%100.00** & Slow tag: Rate: **%66.67**)

Where you running VPN, TOR or anything similar?
Would you be able to run the Python or NodeJS CLI? 

`python3 app.py --cli --mode "fast" --username "pinkdev1" --websites "hackerone" --output "pretty"`
`node app.js --cli --mode "fast" --username "pinkdev1" --websites "hackerone" --output "pretty"`

**Comment by PinkDev1** [comment]
Running that command (`python3 app.py --cli --mode "fast" --username "pinkdev1" --websites "hackerone" --output "pretty"`) I just get the following message:
`[!] Detections are updated every often, make sure to get the most updated ones`
and nothing happens afterwards 👀. I'm not sure what to do

- Python: 3.8.6
- lxml 4.5.2
- BeautifulSoup4 4.6.0
- tld 0.11.11
- pygments 2.3.1

**Comment by giga-a** [comment]
It's because that python script is looking for sites.json not data\sites.json. I added a fix which will be pushed to GitHub within 5h automatically. Thanks for testing that!

**Comment by giga-a** [comment]
How about now?

```
python3 app.py --cli --mode "fast" --username "pinkdev1" --websites "hackerone" --output "pretty"
[!] Detections are updated every often, make sure to get the most updated ones
[Checking] hackerone.com
[Total Profiles Found] 1

{
    "found": 1,
    "link": "https://hackerone.com/pinkdev1",
    "rate": "%100.0",
    "title": "HackerOne"
}
```

**Comment by PinkDev1** [comment]
Just run that and got:
```
Traceback (most recent call last):
  File "app.py", line 31, in <module>
    from langdetect import detect
ModuleNotFoundError: No module named 'langdetect'
```

But after installing that dependency, everything seems to work. Well done!
