### ISSUE TITLE
hanging 

### ISSUE THREAD

**Issue by Incognito-100** [qeeqbox/social-analyzer#30]
it keeps hanging at google Gmail facebook and other random sites

**Comment by giga-a** [comment]
Hey, thanks for submitting your first issue. 
It's not supposed to hang, did you run the web app, NodeJS CLU or Python CLI? 
Also, what tags did you use?

**Comment by Incognito-100** [comment]
I used NodeJS and I used the find user profiles fast and slow and find user profiles special and lookup

**Comment by giga-a** [comment]
I'm looking..

**Comment by giga-a** [comment]
Where you using Tor, VPN or anything similar?
Also, are you be able to run the Pyhton or NodeJS CLI?

node app.js --cli --mode "fast" --username "johndoe" --websites "fosstodon mastodon mstdn" --output "pretty"
or
python app.py --cli --mode "fast" --username "johndoe" --websites "fosstodon mastodon mstdn" --output "pretty"

**Comment by Incognito-100** [comment]
no tor or VPN and I ran the command and it works 
[Detected] 3 Profile[s]

[
  {
    "found": 3,
    "link": "https://mastodon.cloud/@johndoe",
    "rate": "%100.00",
    "title": "johndoe (@johndoe@mastodon.cloud) - mastodon.cloud",
    "language": "English",
    "type": "unavailable"
  },
  {
    "found": 3,
    "link": "https://mastodon.social/@johndoe",
    "rate": "%100.00",
    "title": "johndoe (@johndoe@mastodon.social) - Mastodon",
    "language": "English",
    "type": "unavailable"
  },
  {
    "found": 3,
    "link": "https://mastodon.xyz/@johndoe",
    "rate": "%100.00",
    "title": "johndoe (@johndoe@mastodon.xyz) - Mastodon",
    "language": "English",
    "type": "unavailable"
  }
]

[Unknown] 3 Profile[s]

[
  {
    "link": "https://fosstodon.org/@johndoe",
    "title": "The page you are looking for isn't here.\n - Mastodon",
    "language": "English",
    "type": "unavailable"
  },
  {
    "link": "https://mastodon.technology/@johndoe",
    "title": "The page you are looking for isn't here.\n - Mastodon",
    "language": "English",
    "type": "unavailable"
  },
  {
    "link": "https://mstdn.io/@johndoe",
    "title": "The page you are looking for isn't here.\n - Mastodon",
    "language": "English",
    "type": "unavailable"
  }
]

**Comment by giga-a** [comment]
Good, this means FindUserProfilesFast and GetUserProfilesFast work. 

I added a section in the web app that contains the task logs.
Please let me know, what output do you get that section..

`Cross Ref Issue: 3a279058-f017-458a-b853-13e44bfb6203`

**Comment by giga-a** [comment]
Did that update help?

**Comment by Incognito-100** [comment]
the update fixed it
it doesn't hang anymore
