### ISSUE TITLE
auto title changing to 4216a373-84c1-436d-b8fd-f5c3a627e181

### ISSUE THREAD

**Issue by nkitty8** [qeeqbox/social-analyzer#33]
Hi

**Comment by Wasi110** [comment]
![Screenshot_20210204-055105_Blockchain.jpg](https://user-images.githubusercontent.com/76803798/106829749-97ad6d00-66ae-11eb# -80aa-f921970d949a.jpg)13XT1oTVE# gCwnpyJAbwpF6VLVmKkqvhHzr000000000000000000060283c10d5c4f5b3528a363e9658da85675fd573162b8[]()````
Run


`````
