### ISSUE TITLE
CLI on Windows

### ISSUE THREAD

**Issue by AdrianoCahete** [qeeqbox/social-analyzer#34]
How to run as CLI on Windows?

**Comment by giga-a** [comment]
Hey AdrianoCahete, thanks for submitting your first issue!

I will add examples and follow up with you in the next few hours

**Comment by giga-a** [comment]
Alright, try this

Make sure to download the latest version of social-analyzer

Download Python3 from https://www.python.org/downloads/

Then run:
```
pip3 install lxml BeautifulSoup4 tld pygments langdetect requests
```

Then run this example
```
python3 app.py --cli --mode "fast" --username "johndoe" --websites "youtube pinterest tumblr" --output "pretty"
```

Does it work?

**Comment by AdrianoCahete** [comment]
Worked! :)

For future comparisons: Windows 10 x64

**Comment by giga-a** [comment]
Awesome, let me know if you run into future issues..
Do not forget to share your experience with social-analyzer elsewhere!

**Comment by giga-a** [comment]
Hey, I simplified it more - You can download the pip package called social-analyzer and run it as module anywhere (win or linux)

```
pip install social-analyzer
python -m social-analyzer --cli --mode "fast" --username "johndoe" --websites "youtube pinterest tumblr" --output "pretty"
```

**Comment by AdrianoCahete** [comment]
JFYI: Fully working as a python module! Thanks :)
