### ISSUE TITLE
Question: What’s the likelihood it will be detected as a bot (and blacklisted)? 

### ISSUE THREAD

**Issue by Joshfindit** [qeeqbox/social-analyzer#35]
I don’t see it addressed in the README, but I think it’s an important consideration.

Will users see much more captchas if they run this from their home/work IP? Will some sites block the users from doing queries, and if so: what happens to those results?

**Comment by giga-a** [comment]
Hey Joshfindit, good question and thanks for pointing that out.
I will address that in the next few days and tag this comment!

**Comment by erkinalp** [comment]
> Will users see much more captchas if they run this from their home/work IP?

I tried this 1st hand and I got captcha walls in several of the search results.

**Comment by giga-a** [comment]
> I tried this 1st hand and I got captcha walls in several of the search results.

Hey, what tags & tool did you use API, CLI or the Web APP? This project has many techniques that run based on that and It would be nice to know you ran it.

**Comment by erkinalp** [comment]
I used the Python 3-PIP CLI version. There were dozens of Cloudflare errors in the results.

**Comment by Madsadglad** [comment]
Fast
