### ISSUE TITLE
Find name

### ISSUE THREAD

**Issue by nelllllllh** [qeeqbox/social-analyzer#39]

**Comment by danBamikiya** [comment]
Can you please be specific about the issue?

**Comment by rica200** [comment]
Paano to?

**Comment by giga-a** [comment]
> Paano to?

Kumusta, nahaharap ka ba sa isang isyu sa pagpapatakbo ng tool? (Translated Via Google Translator)

**Comment by rica200** [comment]
Hndi pa nman po. bAgo lang ako dito

**Comment by giga-a** [comment]
Okay, let me know if you run into issues

**Comment by rica200** [comment]
Ok po. Thanks
