### ISSUE TITLE
searching for any name will always return positive results from all websites queried - [Please read the documentation!]

### ISSUE THREAD

**Issue by diehard88** [qeeqbox/social-analyzer#40]
for example, run the following query in which the name is "xxxxxxxxxxxxxxxxxxxxxxx":

 _**python3 -m social-analyzer --cli --mode "fast" --username "xxxxxxxxxxxxxxxxxxxxxx" --websites "all" --output "pretty"**_

will result in this:

> 
link     : https://mixcloud.com/xxxxxxxxxxxxxxxxxxxxxx
title    : Mixcloud
language : unavailable
type     : Audio Streaming
-----------------------
link     : https://nightbot.tv/t/xxxxxxxxxxxxxxxxxxxxxx/commands
title    : Nightbot
language : unavailable
type     : unavailable
....
....
edit
....
....
-----------------------
[failed] 7 Profile[s]
-----------------------
link     : https://codeberg.com/xxxxxxxxxxxxxxxxxxxxxx
-----------------------
link     : https://forum.igromania.ru/member.php?username=xxxxxxxxxxxxxxxxxxxxxx
-----------------------
link     : https://leetcode.com/xxxxxxxxxxxxxxxxxxxxxx
-----------------------
link     : https://pling.com/u/xxxxxxxxxxxxxxxxxxxxxx
-----------------------
link     : https://plug.dj/@/xxxxxxxxxxxxxxxxxxxxxx
-----------------------
link     : https://uid.me/xxxxxxxxxxxxxxxxxxxxxx
-----------------------
link     : https://xxxxxxxxxxxxxxxxxxxxxx.wix.com

>

**Comment by giga-a** [comment]
Hey, thanks for submitting your first issue. Did you read the documentation before opening this issue? This is not a bug, the website returns positive but the profile does not. This project does not only detect profiles but also detects if a webpage exists or not. The entries listed in your example mean that the tool succeeded in getting results from that website. But, the results do not include any hits or do include hits but do not meet the requirements. Also, if everything goes well, then you will see `"status":"good"` `"status":"maybe"`  or `"status":"bad"`

```
          if (temp_value >= 100.00){
            temp_profile.status = "good"
          }
          else if (temp_value >= 50.00 && temp_value < 100.00){
            temp_profile.status = "maybe"
          }
          else{
            temp_profile.status = "bad"
          }
```

Shortly, look for `"status":"good"` to determinate if a profile exists or not

**Comment by diehard88** [comment]
thank you.     

I did RTFM. but not thoroughly....

cheers!

:)

**Comment by giga-a** [comment]
You are very welcome!  Feel free to check\test the other projects 🛵
