### ISSUE TITLE
Jump across e-mails/addresses/linked accounts

### ISSUE THREAD

**Issue by erkinalp** [qeeqbox/social-analyzer#41]
This will allow us to search a person using different usernames across different platforms.

**Comment by UncleStoney2273** [comment]
I'm finished with the updates

**Comment by Madsadglad** [comment]
> This will allow us to search a person using different usernames across different platforms.

And just like me, we appear from everywhere

**Comment by giga-a** [comment]
> This will allow us to search a person using different usernames across different platforms.

Hey erkinalp, what you be able to elaborate more or give a short example?

**Comment by erkinalp** [comment]
For example, you have a user account `user` on YouTube and it lists a connection to `username` account on GitHub. The scanner could utilise such linked accounts in slow mode.

**Comment by giga-a** [comment]
Some old experimental modules extracted text based on patterns. Then, issued different searches based on the extracted text - I will check If it's possible to bring them back or not. 

Closed for now

**Comment by giga-a** [comment]
Extract linked based on regex - Youtube example for now

```
$ python3 app.py --cli --mode "fast" --username "mike" --websites "youtube" --output "pretty"
[!] Detections are updated very often, make sure to get the most up-to-date ones
[!] Temporary Logs Directory /tmp/tmp7ib3v29o
[Checking] youtube.com
[Detected] 1 Profile[s]
-----------------------
found    : 3
link     : https://youtube.com/c/mike/about
rate     : %100.0
status   : good
title    : ---removed--- - YouTube
language : English
type     : Video hosting service
extract  : link:(http://instagram.com/ ---removed---)
-----------------------
```
