### ISSUE TITLE
Costumer email services and reply's as a automated email or message reply

### ISSUE THREAD

**Issue by siamaksk** [qeeqbox/social-analyzer#44]
- [x] - How can i create a html email address or account for auto reply or costumer service section of company???

**Comment by giga-a** [comment]
>     * [x]  - How can i create a html email address or account for auto reply or costumer service section of company???

Hey there, would you be able to tell me what are trying to accomplish?

**Comment by siamaksk** [comment]
Hi dear
Actually i have started building a different construction and land design and development company,by services I provide,firstly our business is very old and known name for our business related and our specific districts area we have experienced and worked as long time.
But We Have A Really undeveloped sections in a company LIKE Our Costumer Service LIKE a Organized and professional business HTML designed  EMAIL and auto Replies or costumer information  data,in a high quality simple email service organization!!?
So ALL i need is the one email provider program or application that  included clouding database for mobile or desktop computer,i can create HTML marketing or news,project samples or request reminders  email,i create then send to my clients as to be connected at first then i go further for many other digital services and inquiries my company is needed very urgent...
Thanks and Regards
Sami karimi
Managing Director of Roy Arte construction
Company
I'm really expecting and excited to receive a response of you
Email:artebuildings@hotmail.com
Phone:0098-9357-191817
0049-152525-00551
[Image.jpeg]

________________________________
از: G <notifications@github.com>
ارسال: سه‌شنبه, فوریهٔ 23, 2021 7:06 قبل‌ازظهر
گیرنده: qeeqbox/social-analyzer
گیرنده کپی: cryptobase; Author
موضوع: Re: [qeeqbox/social-analyzer] Costumer email services and reply's as a automated email or message reply (#44)


Closed #44<https://github.com/qeeqbox/social-analyzer/issues/44>.
