### ISSUE TITLE
Filter out low confidence results by default

### ISSUE THREAD

**Issue by erkinalp** [qeeqbox/social-analyzer#58]
According to my tests, most of the results returned with confidence scores below 60 percent either point to non-existent users or are useless.

**Comment by giga-a** [comment]
Hey, thanks for opening this issue!

Have you tried any of these?

`python3 -m social-analyzer --cli --mode "fast" --username "user" --websites "youtube" --output "pretty" --metadata --extract --trim --filter "good" --profile "detected"`

or 

`python3 app.py --cli --mode "fast" --username "user" --websites "youtube" --output "pretty" --metadata --extract --trim --filter "good" --profile "detected"`

or 

`nodejs app.js --cli --mode "fast" --username "user" --websites "youtube" --output "pretty" --metadata --extract --trim --filter "good" --profile "detected"`

I will think about changing the default value for filter later on

Ref ff241c22-1ef3-4f65-9c4f-ff62ad2961b1

**Comment by giga-a** [comment]
Just for reference, changing that default may break some of the private modules (Not for public)

**Comment by erkinalp** [comment]
> changing that default may break some of the private modules

So, you have more accurate modules that are unpublished?
