### ISSUE TITLE
websites

### ISSUE THREAD

**Issue by sprklingwatrr** [qeeqbox/social-analyzer#59]
Hi, is there a way to search for all the possible websites instead of just the ones you have to input? For example, instead of --websites "instagram facebook youtube" and so on, is there a way to just say --websites "all"?

**Comment by giga-a** [comment]
Hey, try that out! It's already implemented

**Comment by sprklingwatrr** [comment]
Oh cool thank you!

**Comment by giga-a** [comment]
Also, you can filter the status and profile types 

`python3 -m social-analyzer --cli --mode "fast" --username "user" --websites "all" --output "pretty" --metadata --extract --trim --filter "good" --profile "detected"`

or

`python3 app.py --cli --mode "fast" --username "user" --websites "all" --output "pretty" --metadata --extract --trim --filter "good" --profile "detected"`

or

`nodejs app.js --cli --mode "fast" --username "user" --websites "all" --output "pretty" --metadata --extract --trim --filter "good" --profile "detected"`

**Comment by giga-a** [comment]
Let me know if you run into any other issues. 
Do not forget to check the other projects! 🛵
