### ISSUE TITLE
[edited -> Kali Linux install & run] too confusing

### ISSUE THREAD

**Issue by personic75** [qeeqbox/social-analyzer#61]
installed this on kali linux
it was too confusing 
as i could not find CLI or URL Mentioned is not opening 

please do a guided setup for Kali Linux 

help appreciated 

kudos to you effort making life easier

**Comment by giga-a** [comment]
Hey, what's the output of `lsb_release -a`?

**Comment by personic75** [comment]
No lSB available

**Comment by giga-a** [comment]
Alright, 

I have installed it a Web APP on Kali Linux with the following:

```bash
sudo apt-get update
sudo apt-get install -y firefox-esr tesseract-ocr git nodejs npm
git clone https://github.com/qeeqbox/social-analyzer.git
cd social-analyzer
npm install
npm start

#There will be a link on the terminal that points at the interface.
```

I have installed it as python package on Kali Linux with the following:

```bash
sudo apt-get update
sudo apt-get install python3 python3-pip
pip3 install social-analyzer
python3 -m social-analyzer --cli --username "johndoe" --metadata
```

Here is a [wiki](https://github.com/qeeqbox/social-analyzer/wiki/install) for all other installation methods

Does that help?

**Comment by personic75** [comment]
thanks its awesome... thanks for quick help

**Comment by giga-a** [comment]
Great! let me know if you are having any issues running or installing the other projects 🛵
