### ISSUE TITLE
Google API Key and Duck Duck Go API

### ISSUE THREAD

**Issue by mukira** [qeeqbox/social-analyzer#62]
I cannot seem to get the google key and the CS key to work, most likely I'm doing it wrong..what is the correct way to generate those keys from the console.
How do you enable the duck duck go api search option ?

**Comment by giga-a** [comment]
Hey!

Are you using the CLI or GUI?

> I cannot seem to get the google key and the CS key to work, most likely I'm doing it wrong..what is the correct way to generate those keys from the console

The key and cs are not provided, and you would need to create your own. They are part of a platform called google  [Programmable Search Engine](https://programmablesearchengine.google.com/about/). Once create, you can copy them and paste them in the Node GUI settings

> How do you enable the duck duck go api search option?

You can simply enable it by clicking on the [WordInfo](https://github.com/qeeqbox/social-analyzer/wiki/web-app#wordinfo---interacts-with-duckduckgo-api) tag in the Node GUI

**Comment by mukira** [comment]
Nice it works now, sorry but how do you enable to show profile searches screenshots ? blurred or unblurred ?

**Comment by giga-a** [comment]
This tag `Show screenshots of profiles in slow mode` attempts to get a screenshot of the profiles, and they will not be blurred..

I have pushed new updates that simplify choosing those tags in the web interface

<img src="https://raw.githubusercontent.com/qeeqbox/social-analyzer/main/readme/intro_fast.gif" style="max-width:768px"/>

**Comment by giga-a** [comment]
@mukira were you able to enable the profile screenshot?
