### ISSUE TITLE
package folder social-analyzer missing?

### ISSUE THREAD

**Issue by pric0r** [qeeqbox/social-analyzer#68]
`README.md` contains the following instructions:
```
git clone https://github.com/qeeqbox/social-analyzer
cd social-analyzer
```
However, the folder `social-analyzer` seems to be missing.

Is this intended?
And is there a way to pull that missing folder?

**Comment by giga-a** [comment]
Hey @pric0r, are you using windows?
Try this:
```bash
git clone https://github.com/qeeqbox/social-analyzer ./social-analyzer
```

**Comment by pric0r** [comment]
thx for the quick response, @giga-a !

This seems to be a caused by a misunderstanding on my side:
I was reading the `setup.py`, seeing it points at a `social-analyzer` folder.
I was not assuming this path to be defined from outside the project folder.

Now I have seen that all Python-related source code seems to be in `app.py`.

Just curious: is a refactoring to a package folder on your roadmap?

**Comment by giga-a** [comment]
You are welcome!

> I was reading the setup.py, seeing it points at a social-analyzer folder.

You might need to check this script [auto_pip.sh](https://github.com/qeeqbox/social-analyzer/blob/main/auto_pip.sh)

> Just curious: is a refactoring to a package folder on your roadmap?

Sorry, I'm not following?

**Comment by pric0r** [comment]
Ah, thanks for pointing to `auto_pip.sh`.
That script also explains the paths in `setup.py` :-)

Thanks for taking the time to explain.
So this issue is ready to be closed, as far as I am concerned.

But I do not want your question left unanswered:
> Sorry, I'm not following?

To give you some background: my expectation of the layout of a Python project is a bit similar to [this](https://github.com/navdeep-G/samplemod) `sample` project (see also [here](https://docs.python-guide.org/writing/structure/)). As in that example, _the project's main package being placed in the root folder with the same name as the project_ was what I above called a "package folder". 

So if you like, you could share with me your opinion on which project structure your prefer. As said, I am just curious. But it's also totally fine with me if we close this issue, because my original questions is answered.

**Comment by giga-a** [comment]
@pric0r, sorry for the delay! In the past, there were few issues where some users were unable to run this project. The current structure is the result of fixing all those issues.
