### ISSUE TITLE
Wrong command at README

### ISSUE THREAD

**Issue by Sklyvan** [qeeqbox/social-analyzer#69]
At [https://github.com/qeeqbox/social-analyzer#linux-as-python-script](https://github.com/qeeqbox/social-analyzer#linux-as-python-script) the last line should be:
```bash
python3 app.py --username "johndoe" --metadata --top 100
```

**Comment by giga-a** [comment]
Hey @Sklyvan! Do you want to create PR for that? (I will merge it)
