### ISSUE TITLE
Temp log files generated

### ISSUE THREAD

**Issue by jasperan** [qeeqbox/social-analyzer#74]
Hello, I've been using social analyzer programatically and it looks like, after a couple of days running 24/7, it's generated about 2TB of data in the /tmp directory. Do you know any way to avoid logs being generated automatically by the program?

**Comment by giga-a** [comment]
@jasperan yes! 

I'm going to add an 2 options:
1) to remove the task temp files and
2) keeping only the metadata of the task but not the entire process

Are you using the Python CLI or NodeJS?

**Comment by jasperan** [comment]
I'm using your Python client library:

```
def process_social_analyzer(username):
    SocialAnalyzer = import_module("social-analyzer").SocialAnalyzer(silent=True)
    results = SocialAnalyzer.run_as_object(username=username, silent=True)
    list_of_sites = list()
    for x in results.get('detected'):
        if ('wiki' not in x.get('link')) and ('User:') not in x.get('link'):
            list_of_sites.append(x.get('link'))
    print('[DBG] USER {} SITES {}'.format(username, len(list_of_sites)))
    return list_of_sites
```

**Comment by giga-a** [comment]
@jasperan will push a new fix soon (Ref f43291547b70)

**Comment by giga-a** [comment]
@jasperan 

The logs are disabled by default, if you want logs then you will need to add `logs=True`
```python
results = SocialAnalyzer.run_as_object(username=username, silent=True, logs=True)
```

**Comment by jasperan** [comment]
Thank you @giga-a !

**Comment by giga-a** [comment]
@jasperan - You are welcome, feel free to share your experience using social-analyzer!

**Comment by jasperan** [comment]
I will make sure to write an article of the use I've made from your repository when I get some free time (and permission!).

Kind regards.
