### ISSUE TITLE
Docker-compose install instructions outdated

### ISSUE THREAD

**Issue by Jiab77** [qeeqbox/social-analyzer#77]
## Issue

When working this week on your project, I saw that `docker-compose` download and install command with `curl` is pointing to an outdated version of `docker-compose`.

## Where

The issue is located in the project wiki here: https://github.com/qeeqbox/social-analyzer/wiki/install#docker-compose

## What's need to be changed?

According to the [official documentation](https://docs.docker.com/compose/install/), the line:

```
sudo curl -L "https://github.com/docker/compose/releases/download/1.26.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
```

Should be replaced by:

```
sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
```

## Additional changes for docker-compose

Since you've accepted and merged my [pull request](https://github.com/qeeqbox/social-analyzer/pull/75), why not add the following?

```bash
# By default (2 CPU cores)
docker-compose -f docker-compose.yml up --build

# Using all available CPU cores
echo "CPU_CORES=`nproc`" > .env ; docker-compose -f docker-compose.yml up --build

# Using only some CPU cores (if more than 4)
echo "CPU_CORES=4" > .env ; docker-compose -f docker-compose.yml up --build
```

This would make the `docker-compose` install instructions from this:

```bash
sudo apt-get update
sudo apt-get install -y docker.io git curl
sudo curl -L "https://github.com/docker/compose/releases/download/1.26.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
git clone https://github.com/qeeqbox/social-analyzer.git
cd social-analyzer
docker-compose -f docker-compose.yml up --build
```

To that:

```bash
# Install updates, docker-compose and project
sudo apt-get update
sudo apt-get install -y docker.io git curl
sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
git clone https://github.com/qeeqbox/social-analyzer.git
cd social-analyzer

# Default deployment (2 CPU cores)
docker-compose -f docker-compose.yml up --build

# Deploy and use all available CPU cores
echo "CPU_CORES=`nproc`" > .env ; docker-compose -f docker-compose.yml up --build

# Deploy and use only some CPU cores (if more than 4)
echo "CPU_CORES=4" > .env ; docker-compose -f docker-compose.yml up --build
```

> Note: My [pull request](https://github.com/qeeqbox/social-analyzer/pull/75) has been deployed with `docker-compose` version `1.29.2` which is the latest release from the `1.x.x` branch as of writing. 

## Warning

Docker has recently released the [compose](https://github.com/docker/compose) plugin as `docker-compose` __V2__ and [compose-switch](https://github.com/docker/compose-switch) to smoothly handle the transition from the version 1.x.x (`docker-compose`) to the version 2.x.x (`docker compose`).

So, maybe it would be useful to say that this project has been tested and works on V1 (`docker-compose`) but probably not with V2 (`docker compose`) or needs additional testing to be documented.

I was unsure myself which version I would use knowing that the currently documented version `1.26.2` was outdated and so wanted to use the latest one and then I saw that a __V2__ where out but was working differently and was no longer a single binary but now a `docker` plugin and `docker-switch` should be used to handle the transition.

## Comments

I wanted to create a pull request along this issue but I could not find any `edit` links in the Wiki 😅

**Comment by giga-a** [comment]
@Jiab77 Thanks for opening this detailed issue!! - Yeah, I wish there was an edit button for wiki pages 😀

Out of curiosity, have you tried cloning the wiki? `git clone https://github.com/qeeqbox/social-analyzer.wiki.git` (I had never tried this before)

**Comment by Jiab77** [comment]
@giga-a, you're very welcome! As I said already, I really like your project, I find it very useful!

About the wiki, I'm still pretty novice to that but you're right, I could have tried to clone the wiki. I just found where it was not that you've pointed to it 😅 

Do you want me to try to fork the wiki and push my suggested changes so that you can review them?

I've never forked nor updated a wiki yet so it's pretty new to me 😄

**Comment by giga-a** [comment]
@Jiab77 :) It's okay - I have already updated them!

**Comment by Jiab77** [comment]
@giga-a, woow thank you so much! I just checked in the doc and it's render very well :)
