### ISSUE TITLE
Dash typo in wiki

### ISSUE THREAD

**Issue by ferranolivera** [qeeqbox/social-analyzer#82]
Hey,

There are a couple of dashes (–) instead of hyphens (-) in wiki's _install.md_. When copy-pasting the commands, this results in unrecognized arguments.

You might check: [044aa5b](https://github.com/ferranolivera/social-analyzer/wiki/install/044aa5b99ea57b01479296a04d24dcf91c6365a9).

Thanks for your work!

**Comment by giga-a** [comment]
@ferranolivera, thanks! 
Good catch, I fixed the ones in install.md 
Do you want to fix the ones in README.md? If you raise a PR, I will merge it?
Giga

**Comment by ferranolivera** [comment]
Sure! I just raised it.

**Comment by giga-a** [comment]
Merged, if you find any issues in this or the other projects, let me know!
