### ISSUE TITLE
social-analyzer stops working?

### ISSUE THREAD

**Issue by Svea99** [qeeqbox/social-analyzer#86]
Since yesterday I have the problem that social-analyzer wont give any output. I can run it (win x64 / node / firefox), start the search but than it stucked at the processing screen. 

I recently updatete node to 16.15.0 but I got the same issue again.

I tryed social-analyzer in firefox and chromium based browsers but again the same issue. 

Any advices?

**Comment by TurfJakkals** [comment]
I'm also experiencing this problem.
Windows standard WEB APP

**Comment by giga-a** [comment]
Hey @TurfJakkals & @Svea99 

Thanks for reporting that, I'm looking..

**Comment by giga-a** [comment]
@TurfJakkals @Svea99 download it again and try?

**Comment by TurfJakkals** [comment]
> download it again and try?

Working perfectly.
What a champ. Thank you!

**Comment by giga-a** [comment]
@TurfJakkals Great, feel free to share your experience with social-analyzer!

**Comment by giga-a** [comment]
@Svea99 if you still having the issue, let me know so I re

**Comment by Svea99** [comment]
> @Svea99 if you still having the issue, let me know so I re-open this issue..

thx for your fast help!

worked!

Idk why but after the node update it looks like I messed up some installation folders. build up from scratch with the new download = problem solved!
