### ISSUE TITLE
fetch that never ends

### ISSUE THREAD

**Issue by osinter456** [qeeqbox/social-analyzer#90]
Hi with docker i have a fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz that never ends
I have an Ubuntu.

docker build -t social-analyzer . && docker run -p 9005:9005 -it social-analyzer
Sending build context to Docker daemon  97.62MB
Step 1/6 : FROM node:14.15.3-alpine3.12
14.15.3-alpine3.12: Pulling from library/node
801bfaa63ef2: Pull complete 
10e8f660b8bc: Pull complete 
68b982bd1bfc: Pull complete 
d15bdb5ba212: Pull complete 
Digest: sha256:3fcd65a94320827a74eacd80da24a190f2c3e65ce0f66e4fe7764629f11afde3
Status: Downloaded newer image for node:14.15.3-alpine3.12
 ---> 46c3eb6e27e9
Step 2/6 : WORKDIR /usr/src/app
 ---> Running in 9e0fc39f7f89
Removing intermediate container 9e0fc39f7f89
 ---> 2c155c8cee42
Step 3/6 : COPY . .
 ---> 0b71da4b4d83
Step 4/6 : RUN apk update &&   apk add --no-cache firefox-esr &&   npm install lodash &&   npm install --loglevel=error
 ---> Running in 0c6da9e380ba
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
v3.12.12-40-gdc5d0f0e3f [http://dl-cdn.alpinelinux.org/alpine/v3.12/main]
v3.12.12-30-g96b07a1c68 [http://dl-cdn.alpinelinux.org/alpine/v3.12/community]
OK: 12771 distinct packages available
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz

Best regards

**Comment by giga-a** [comment]
@osinter456 thanks for opening this issue.

It worked on my end

```bash
Step 4/6 : RUN apk update &&   apk add --no-cache firefox-esr &&   npm install lodash &&   npm install --loglevel=error
 ---> Running in 47c30c1443ff
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
v3.12.12-45-g8116a127ec [http://dl-cdn.alpinelinux.org/alpine/v3.12/main]
v3.12.12-30-g96b07a1c68 [http://dl-cdn.alpinelinux.org/alpine/v3.12/community]
OK: 12771 distinct packages available
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
(1/73) Installing libxau (1.0.9-r0)
(2/73) Installing libbsd (0.10.0-r0)
(3/73) Installing libxdmcp (1.1.3-r0)
(4/73) Installing libxcb (1.14-r1)
(5/73) Installing libx11 (1.6.12-r1\
...
```

Maybe DNS issue?
